server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identityservice"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update          #thay doi ve entity (@Entity), tu dong generate 1 bang moi, thuc te thi se chay script de tao table
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

jwt:
  signerKey: "HbaDIZtfLJ6fbn85qVkTu4hjwaDF0JtHf2r2AU1/HdqsbCV71BZWSdHJhnY9d7lS"
  valid-duration: 10 #in seconds
  refreshable-duration: 120 #in minutes

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG